language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk14

after_success:
  - mvn javadoc:javadoc
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml
